name: face_classification_edit_cpu
channels: 
  - conda-forge
  - defaults
  - pytorch
dependencies: 
  - conda-forge::python=3.9.12
  - numpy-base==1.21.5
  - pip
  - pytorch::pytorch=1.12.1
  - pytorch::torchvision=0.13.1
  - pytorch::cpuonly
  - pip:
    - mlchain==0.3.0
    - loguru
    - pillow==9.2.0
    - streamlit==1.12.2
